# Generated by Django 4.1.4 on 2022-12-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='shrt_url',
            new_name='short_url',
        ),
    ]
