# Generated by Django 4.1.4 on 2022-12-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0002_rename_shrt_url_shorturl_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='TD',
            new_name='Creation_Time_And_Date',
        ),
    ]
