# Generated by Django 4.1.4 on 2022-12-31 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0003_rename_td_shorturl_creation_time_and_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='Creation_Time_And_Date',
        ),
    ]
